version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: spectrum-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_POSTGRES_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spectrum-network

  mongo-db:
    image: mongo:7.0
    container_name: spectrum-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - spectrum-network

volumes:
  postgres_data:
  mongo_data:
  
networks:
  spectrum-network:
    driver: bridge