using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Spectrum.API.Dtos.Media;
using Spectrum.API.Services.Storage;
using System.Threading.Tasks;

namespace Spectrum.API.Controllers
{
    /// <summary>
    /// Entry point for managing media file uploads.
    /// Handles HTTP routing and status codes, delegating all validation and storage logic to specialized services.
    /// </summary>
    [ApiController]
    [Route("api/[controller]")]
    [Produces("application/json")]
    [Authorize]
    public class MediaController : ControllerBase
    {
        private readonly IImageStorageService imageStorageService;
        private readonly IVideoStorageService videoStorageService;

        /// <summary>
        /// Initializes a new instance of the <see cref="MediaController"/> class.
        /// </summary>
        /// <param name="imageStorageService">The service handling single-part image uploads.</param>
        /// <param name="videoStorageService">The service handling chunked video uploads.</param>
        public MediaController(IImageStorageService imageStorageService, IVideoStorageService videoStorageService)
        {
            this.imageStorageService = imageStorageService;
            this.videoStorageService = videoStorageService;
        }

        /// <summary>
        /// Uploads an image file (JPG/PNG) directly to the specified storage folder.
        /// </summary>
        /// <param name="file">The image file payload.</param>
        /// <param name="folder">The target folder name (defaults to "imagesReviews").</param>
        /// <returns>The public access URL for the uploaded image.</returns>
        /// <response code="200">The image was successfully validated and uploaded.</response>
        /// <response code="400">The image failed size or format validations.</response>
        [HttpPost("upload-image")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status400BadRequest)]
        public async Task<IActionResult> UploadImage(IFormFile file, [FromQuery] string folder = "imagesReviews")
        {
            var url = await imageStorageService.UploadImageAsync(file, folder);
            return Ok(new { url });
        }

        /// <summary>
        /// Validates a video file and initiates an AWS S3 multipart upload session.
        /// </summary>
        /// <param name="file">The full video file used for preliminary metadata validation.</param>
        /// <returns>The initialization details including the active UploadId and KeyName.</returns>
        /// <response code="200">The video metadata is valid and the session has started.</response>
        /// <response code="400">The video exceeds duration or size limits, or has an invalid format.</response>
        [HttpPost("clips/start")]
        [ProducesResponseType(typeof(MultipartInitResponseDto), StatusCodes.Status200OK)]
        [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status400BadRequest)]
        public async Task<IActionResult> StartVideoUpload(IFormFile file)
        {
            // We pass the file to validate duration and size before talking to AWS S3
            var response = await videoStorageService.StartVideoUploadAsync(file, "clips");
            return Ok(response);
        }

        /// <summary>
        /// Uploads a single 5MB byte chunk to an active multipart upload session.
        /// </summary>
        /// <param name="file">The individual binary chunk payload.</param>
        /// <param name="uploadId">The active session identifier.</param>
        /// <param name="partNumber">The sequential position of the chunk (1-indexed).</param>
        /// <param name="keyName">The exact path of the object in S3.</param>
        /// <returns>The unique ETag generated by the storage provider for this chunk.</returns>
        /// <response code="200">The chunk was successfully received and stored in S3.</response>
        /// <response code="400">The chunk size exceeds the strict streaming constraints.</response>
        [HttpPost("clips/upload-chunk")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status400BadRequest)]
        public async Task<IActionResult> UploadVideoChunk(
            IFormFile file,
            [FromQuery] string uploadId,
            [FromQuery] int partNumber,
            [FromQuery] string keyName)
        {
            var eTag = await videoStorageService.UploadVideoChunkAsync(file, uploadId, partNumber, keyName);
            return Ok(new { eTag });
        }

        /// <summary>
        /// Finalizes the multipart upload by ordering the storage provider to assemble all chunks.
        /// </summary>
        /// <param name="request">The complete assembly payload containing the part mapping and session IDs.</param>
        /// <returns>The final public access URL for the assembled video file.</returns>
        /// <response code="200">All chunks were successfully merged into a single file.</response>
        [HttpPost("clips/complete")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        public async Task<IActionResult> CompleteVideoUpload([FromBody] CompleteUploadRequestDto request)
        {
            var url = await videoStorageService.CompleteVideoUploadAsync(request);
            return Ok(new { url });
        }
    }
}